### ISSUE TITLE
[Q]: merge with another scrapper

### ISSUE THREAD

**Issue by stokito** [wranders/doh-list#1]
### Question

Here is a scrapper that is mentioned in the Wiki page itself https://gist.github.com/kimbo/dd65d539970e3a28a10628f15398247b
Maybe you guys can collaborate and merge your scripts?

There is also another list called DNSCrypt.info that also generates a list of DoH providers:
https://github.com/DNSCrypt/dnscrypt-resolvers/issues/842

Maybe you can also collaborate on this.
Thank you

**Comment by wranders** [comment]
I'm not sure there's much to merge with the Gist since it's written in Python and the script here was intentionally written using only POSIX utilities for portability. [update-doh-list.sh](https://github.com/wranders/doh-list/blob/master/update-doh-list.sh) was originally part of a cronjob on my old Pi-Hole.

But, I have been considering pooling more sources than just the curl wiki so the list is more comprehensive. Allowing for all the tools available on Actions runners instead of just POSIX tools would open up the possibility to use sources like the DNSCrypt project you linked to.

Are there any other lists you can think of?

**Comment by stokito** [comment]
thank you for the clarification. I don't think that is makes sense to process more lists because the curl wiki is already covers all of them.
JFYI: you can get list of providers in JSON form https://download.dnscrypt.info/dnscypt-resolvers/json/public-resolvers.json
